### ISSUE TITLE
[Bug]: Join Late Screen is Blank

### ISSUE THREAD

**Issue by DAKKA-WAAAGH** [Darkrp-community/OpenKeep#268] opened 2024-06-28 23:50 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

![image](https://github.com/Darkrp-community/OpenKeep/assets/34065421/f03414ea-31ba-42dd-a224-5fd3b9b0235e)

Upon hearing in genchat, I went to check for myself. Sure enough, it's blank.
Current TMs:
- #247 
- #216 
- #265

### How to reproduce

1. Join server
2. Click JOINLATE

### Round ID

Sherax294-22.12.13

### Staff ckey

N/A

**Comment by casualspacestation14enjoyer** [comment] 2024-06-29 10:25
duplicate of #269

**Closed by casualspacestation14enjoyer** 2024-06-29 10:25 UTC
