### ISSUE TITLE
[Bug]: Cannot Latejoin Server

### ISSUE THREAD

**Issue by Max-023** [Darkrp-community/OpenKeep#269] opened 2024-06-28 23:51 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Location

RogueTown

### Describe the issue

When clicking the join late button, the role selection screen doesn't display any roles. Drifter queue works (Stonekeep has fallen), at least. Tried swapping characters, switching patrons, etc. and the role select didn't fix itself. Not that it is likely necessary, but here is a screenshot below.

![image](https://github.com/Darkrp-community/OpenKeep/assets/42359139/12928570-7edd-4ba9-b999-0eb75e3ec941)

### How to reproduce

Join the server after it started, try to join.

### Round ID

Sherax294-22.12.13

**Comment by casualspacestation14enjoyer** [comment] 2024-06-29 10:24
This is an issue with admins using the Start-Now verb, not caused by any test merged PRs.

**Closed by casualspacestation14enjoyer** 2024-06-29 10:24 UTC
