### ISSUE TITLE
[Bug]: Inverted visor helmet bug

### ISSUE THREAD

**Issue by BadAtThisGame302** [Darkrp-community/OpenKeep#607] opened 2024-08-28 19:05 UTC
### Checks

- [X] I have searched the bug with a few keywords, and I confirm this bug was not yet reported.

### Map

RogueTown, DakkaTown

### Describe the issue

You are unknown when the visor is open, you are named when the visor is shut.

### How to reproduce

Right click any visored helm.

### Round ID

Tapir733-18.10.39

**Comment by NPC1314** [comment] 2024-08-31 09:19
Caused by changes made to helmets in https://github.com/Darkrp-community/OpenKeep/pull/526 or a PR close to it in time.

**Comment by NPC1314** [comment] 2024-09-01 11:36
Considering just nuking on hip slots for helmets so we can just use not complicated procs that causes more issues.

**Comment by NPC1314** [comment] 2024-09-18 10:45
#743 should fix this

**Comment by ThePainkiller** [comment] 2024-09-19 09:35
Closed as completed by #743 .

**Closed by ThePainkiller** 2024-09-19 09:35 UTC
